# Generated by Django 5.2.6 on 2026-03-02 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FisioProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Procedimento (Fisio)',
                'verbose_name_plural': 'Procedimentos (Fisio)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FisioReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('h6', '6h'), ('h12', '12h')], max_length=3)),
                ('attendances', models.PositiveIntegerField()),
                ('refusals', models.PositiveIntegerField(default=0)),
                ('body_part', models.CharField(max_length=80)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fisio_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório Fisio',
                'verbose_name_plural': 'Relatórios Fisio',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FisioReportProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(choices=[('membro_superior_esquerdo', 'Membro Superior Esquerdo'), ('membro_superior_direito', 'Membro Superior Direito'), ('membro_inferior_esquerdo', 'Membro Inferior Esquerdo'), ('membro_inferior_direito', 'Membro Inferior Direito'), ('coluna_cervical', 'Coluna Cervical'), ('coluna_toracica', 'Coluna Torácica'), ('coluna_lombar', 'Coluna Lombar'), ('coluna_sacro', 'Coluna Sacro')], max_length=80)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_items', to='fisioterapia.fisioprocedure')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='fisioterapia.fisioreport')),
            ],
            options={
                'verbose_name': 'Detalhe do Relatório (Fisio)',
                'verbose_name_plural': 'Detalhes do Relatório (Fisio)',
                'indexes': [models.Index(fields=['report'], name='fisioterapi_report__f19454_idx'), models.Index(fields=['procedure'], name='fisioterapi_procedu_0a93cf_idx')],
            },
        ),
    ]
