# Generated by Django 5.2.6 on 2026-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisioreport',
            name='refusals_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fisioreportprocedure',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
