# Generated by Django 5.2.6 on 2026-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapia', '0003_fisiouseraudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisiouseraudit',
            name='action',
            field=models.CharField(choices=[('deactivated', 'Desativado'), ('reactivated', 'Reativado')], max_length=20),
        ),
    ]
