# Generated by Django 5.2.7 on 2025-10-07 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='Nome do Paciente')),
                ('procedure_name', models.CharField(max_length=255, verbose_name='Nome do Procedimento')),
                ('scheduled_date', models.DateField(verbose_name='Data Agendada')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('EM_ANDAMENTO', 'Em Andamento')], default='AGENDADA', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Cirurgia',
                'verbose_name_plural': 'Cirurgias',
            },
        ),
        migrations.CreateModel(
            name='BillingData',
            fields=[
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='billing_data', serialize=False, to='core.surgery')),
                ('invoice_code', models.CharField(blank=True, max_length=100, verbose_name='Código da Fatura')),
                ('is_billed', models.BooleanField(default=False, verbose_name='Faturado?')),
            ],
            options={
                'verbose_name': 'Dados de Faturamento',
            },
        ),
        migrations.CreateModel(
            name='CMEData',
            fields=[
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cme_data', serialize=False, to='core.surgery')),
                ('sterilization_code', models.CharField(blank=True, max_length=100, verbose_name='Código de Esterilização')),
                ('material_status', models.CharField(blank=True, max_length=100, verbose_name='Status do Material')),
            ],
            options={
                'verbose_name': 'Dados da CME',
            },
        ),
        migrations.CreateModel(
            name='NursingChecklist',
            fields=[
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nursing_checklist', serialize=False, to='core.surgery')),
                ('pre_op_checklist_completed', models.BooleanField(default=False, verbose_name='Checklist Pré-Operatório Completo?')),
                ('post_op_checklist_completed', models.BooleanField(default=False, verbose_name='Checklist Pós-Operatório Completo?')),
                ('notes', models.TextField(blank=True, verbose_name='Observações de Enfermagem')),
            ],
            options={
                'verbose_name': 'Checklist de Enfermagem',
            },
        ),
        migrations.CreateModel(
            name='OPMEData',
            fields=[
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='opme_data', serialize=False, to='core.surgery')),
                ('material_used', models.TextField(blank=True, verbose_name='Material Utilizado')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo (R$)')),
            ],
            options={
                'verbose_name': 'Dados de OPME',
            },
        ),
        migrations.CreateModel(
            name='RegulationData',
            fields=[
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='regulation_data', serialize=False, to='core.surgery')),
                ('entry_date', models.DateField(verbose_name='Data de Entrada no NIR')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado?')),
                ('notes', models.TextField(blank=True, verbose_name='Observações do NIR')),
            ],
            options={
                'verbose_name': 'Dados de Regulação (NIR)',
            },
        ),
        migrations.CreateModel(
            name='SurgicalData',
            fields=[
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='surgical_data', serialize=False, to='core.surgery')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Início da Cirurgia')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Cirurgia')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Sala Cirúrgica')),
            ],
            options={
                'verbose_name': 'Dados do Centro Cirúrgico',
            },
        ),
    ]
