# Generated by Django 5.2.7 on 2025-10-07 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cmedata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nursingchecklist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='opmedata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='regulationdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='surgery',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Cirurgia', 'verbose_name_plural': 'Cirurgias'},
        ),
        migrations.AlterModelOptions(
            name='surgicaldata',
            options={},
        ),
        migrations.RemoveField(
            model_name='cmedata',
            name='material_status',
        ),
        migrations.RemoveField(
            model_name='cmedata',
            name='sterilization_code',
        ),
        migrations.RemoveField(
            model_name='nursingchecklist',
            name='post_op_checklist_completed',
        ),
        migrations.RemoveField(
            model_name='nursingchecklist',
            name='pre_op_checklist_completed',
        ),
        migrations.RemoveField(
            model_name='opmedata',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='opmedata',
            name='material_used',
        ),
        migrations.AddField(
            model_name='cmedata',
            name='material_sterilized',
            field=models.BooleanField(default=False, verbose_name='Material Esterilizado?'),
        ),
        migrations.AddField(
            model_name='cmedata',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da CME'),
        ),
        migrations.AddField(
            model_name='cmedata',
            name='sterilization_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Esterilização'),
        ),
        migrations.AddField(
            model_name='nursingchecklist',
            name='consent_form_signed',
            field=models.BooleanField(default=False, verbose_name='Termo de Consentimento Assinado?'),
        ),
        migrations.AddField(
            model_name='nursingchecklist',
            name='patient_fasting',
            field=models.BooleanField(default=False, verbose_name='Paciente em Jejum?'),
        ),
        migrations.AddField(
            model_name='nursingchecklist',
            name='pre_op_medication_given',
            field=models.BooleanField(default=False, verbose_name='Medicação Pré-operatória Administrada?'),
        ),
        migrations.AddField(
            model_name='opmedata',
            name='is_authorized',
            field=models.BooleanField(default=False, verbose_name='Autorizado?'),
        ),
        migrations.AddField(
            model_name='opmedata',
            name='materials_list',
            field=models.TextField(blank=True, null=True, verbose_name='Lista de Materiais OPME'),
        ),
        migrations.AddField(
            model_name='opmedata',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='surgicaldata',
            name='surgeon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cirurgião'),
        ),
        migrations.AlterField(
            model_name='billingdata',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código da Fatura'),
        ),
        migrations.AlterField(
            model_name='billingdata',
            name='surgery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.surgery', verbose_name='Cirurgia'),
        ),
        migrations.AlterField(
            model_name='cmedata',
            name='surgery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.surgery', verbose_name='Cirurgia'),
        ),
        migrations.AlterField(
            model_name='nursingchecklist',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações de Enfermagem'),
        ),
        migrations.AlterField(
            model_name='nursingchecklist',
            name='surgery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.surgery', verbose_name='Cirurgia'),
        ),
        migrations.AlterField(
            model_name='opmedata',
            name='surgery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.surgery', verbose_name='Cirurgia'),
        ),
        migrations.AlterField(
            model_name='regulationdata',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrada na Regulação'),
        ),
        migrations.AlterField(
            model_name='regulationdata',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='regulationdata',
            name='surgery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.surgery', verbose_name='Cirurgia'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='procedure_name',
            field=models.CharField(max_length=200, verbose_name='Nome do Procedimento'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='scheduled_date',
            field=models.DateTimeField(verbose_name='Data Agendada'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=10),
        ),
        migrations.AlterField(
            model_name='surgicaldata',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sala Cirúrgica'),
        ),
        migrations.AlterField(
            model_name='surgicaldata',
            name='surgery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.surgery', verbose_name='Cirurgia'),
        ),
    ]
