# Generated by Django 5.2.7 on 2025-10-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_billingdata_options_alter_cmedata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='motivo_institucional',
            field=models.CharField(blank=True, choices=[('FALTA_INSUMOS', 'Falta de insumos'), ('FALTA_EQUIPAMENTO', 'Falta de equipamento'), ('EQUIPAMENTO_DEFEITO', 'Equipamento com defeito'), ('INDISPONIBILIDADE_PROFISSIONAL', 'Indisponibilidade de profissional')], max_length=50, null=True, verbose_name='Motivo Institucional'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='motivo_paciente',
            field=models.CharField(blank=True, choices=[('MEDICACAO', 'Medicação'), ('QUEBRA_JEJUM', 'Quebra de jejum'), ('EXAMES_ALTERADOS', 'Exames alterados')], max_length=50, null=True, verbose_name='Motivo do Paciente'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='observacoes_cancelamento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observações do Cancelamento'),
        ),
    ]
