# Generated by Django 5.2.7 on 2025-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_surgery_motivo_institucional_surgery_motivo_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='setor_cancelamento',
            field=models.CharField(blank=True, choices=[('NIR', 'NIR (Regulação)'), ('GENF', 'GENF (Enfermagem)'), ('CC', 'CC (Centro Cirúrgico)'), ('OUTRO', 'Outro')], max_length=10, null=True, verbose_name='Setor Responsável pelo Cancelamento'),
        ),
    ]
