# Generated by Django 5.2.7 on 2025-10-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_surgery_setor_cancelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicaldata',
            name='checklist_cirurgia_segura',
            field=models.BooleanField(default=False, verbose_name='Checklist de Cirurgia Segura Realizado?'),
        ),
    ]
