# Generated by Django 5.2.6 on 2025-10-15 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_surgicaldata_checklist_cirurgia_segura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Setor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Indicador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição / Fórmula de Cálculo')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='core.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['sector', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Período (Mês e Ano)')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Registrado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='core.indicator', verbose_name='Indicador')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Dado de Indicador',
                'verbose_name_plural': 'Dados de Indicadores',
                'ordering': ['-period', 'indicator'],
                'unique_together': {('indicator', 'period')},
            },
        ),
    ]
