# Generated by Django 5.2.7 on 2025-10-15 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_sector_indicator_indicatordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Grupo de Permissão'),
        ),
    ]
