# Generated by Django 5.2.6 on 2025-10-23 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sector_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='Identificador do Leito')),
                ('clinic', models.CharField(max_length=100, verbose_name='Clínica')),
                ('category', models.CharField(choices=[('NORMAL', 'Normal'), ('INFECTADO', 'Infectado'), ('EXTENSAO', 'Extensão'), ('EXTRA', 'Extra')], default='NORMAL', max_length=20, verbose_name='Categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='Leito Ativo?')),
            ],
            options={
                'verbose_name': 'Leito',
                'verbose_name_plural': 'Leitos',
                'ordering': ['clinic', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('medical_record_number', models.CharField(max_length=50, unique=True, verbose_name='Número do Prontuário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(verbose_name='Data/Hora de Admissão')),
                ('discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Saída')),
                ('procedure_planned', models.CharField(blank=True, max_length=255, null=True, verbose_name='Procedimento Previsto')),
                ('current_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Atual')),
                ('expected_surgery_date', models.DateField(blank=True, null=True, verbose_name='Previsão Cirúrgica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='core.bed', verbose_name='Leito')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hospitalizations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='core.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Internação/Ocupação',
                'verbose_name_plural': 'Internações/Ocupações',
                'ordering': ['-admission_date'],
            },
        ),
    ]
