# Generated by Django 5.2.6 on 2025-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bed_patient_hospitalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalization',
            name='avaliacao_nurse_nutri',
            field=models.TextField(blank=True, null=True, verbose_name='Avaliação Nurse/Nutri'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='avaliacao_social',
            field=models.TextField(blank=True, null=True, verbose_name='Avaliação Social'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='convenio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Convênio'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='exames_pendentes',
            field=models.TextField(blank=True, null=True, verbose_name='Exames Pendentes'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='hipotese_diagnostica',
            field=models.TextField(blank=True, null=True, verbose_name='Hipótese Diagnóstica'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='internacao_prolongada',
            field=models.BooleanField(blank=True, null=True, verbose_name='Internação Prolongada'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='necessidade_isolamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Necessidade de Isolamento'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='nome_cirurgiao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Cirurgião'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='numero_atendimento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº do Atendimento'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='opme_necessario',
            field=models.BooleanField(blank=True, null=True, verbose_name='OPME Necessário'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='parecer_especialidade',
            field=models.TextField(blank=True, null=True, verbose_name='Parecer de Especialidade'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='precaucoes_especificas',
            field=models.TextField(blank=True, null=True, verbose_name='Precauções Específicas'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='risco_cirurgico_alto',
            field=models.BooleanField(blank=True, null=True, verbose_name='Risco Cirúrgico Alto'),
        ),
        migrations.AlterField(
            model_name='indicatordata',
            name='period',
            field=models.DateField(verbose_name='Período'),
        ),
    ]
