# Generated by Django 5.2.6 on 2025-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reception_attendance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientextra',
            name='cns',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CNS'),
        ),
        migrations.AlterField(
            model_name='patientextra',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
