# Generated by Django 5.2.6 on 2025-11-17 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_patientextra_cns_alter_patientextra_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EXAME', 'Exames'), ('LAUDO', 'Laudos'), ('DOCUMENTO', 'Documentos Pessoais'), ('REQUERIMENTO', 'Requerimentos'), ('ATESTADO', 'Atestados'), ('OUTRO', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('document', models.FileField(upload_to='patient_documents/%Y/%m/', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.patient', verbose_name='Paciente')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento do Paciente',
                'verbose_name_plural': 'Documentos do Paciente',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
