# Generated by Codex on 2026-02-25
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evento', models.DateField(verbose_name='Data do evento')),
                ('pulseira_identificacao', models.BooleanField(default=False)),
                ('identificacao_medicacao', models.BooleanField(default=False)),
                ('risco_queda', models.BooleanField(default=False)),
                ('lesao_pressao', models.BooleanField(default=False)),
                ('flebite', models.BooleanField(default=False)),
                ('tempo_acesso_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo_roupa_cama_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('identificacao_leito', models.BooleanField(default=False)),
                ('nao_conformidade_estruturas', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adverse_reports', to='auth.user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adverse_event_reports', to='core.patient')),
            ],
            options={
                'verbose_name': 'Evento Adverso',
                'verbose_name_plural': 'Eventos Adversos',
                'ordering': ['-date_evento', '-created_at'],
            },
        ),
    ]
