# Generated by Django 4.2.30 on 2026-08-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_adverse_event_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('direcao', 'Direção'), ('diretoria', 'Diretoria'), ('gerencia', 'Gerência'), ('nucleo', 'Núcleo'), ('assistencial', 'Assistencial'), ('administrativo', 'Administrativo'), ('unidade', 'Unidade'), ('comissao', 'Comissão')], max_length=20, verbose_name='Tipo')),
                ('nivel', models.PositiveSmallIntegerField(choices=[(0, 'Direção Máxima'), (1, 'Diretorias e Adjuntos'), (2, 'Gerências, Núcleos e Centrais'), (3, 'Unidades Especializadas')], verbose_name='Nível hierárquico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='core.orgunit', verbose_name='Superior imediato')),
            ],
            options={
                'verbose_name': 'Setor do Organograma',
                'verbose_name_plural': 'Organograma — Setores',
                'ordering': ['nivel', 'nome'],
            },
        ),
    ]
