# Generated by Django 5.2.6 on 2026-08-27 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_orgunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CensoImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('csv', 'Upload de CSV'), ('google_sheets', 'Google Sheets')], max_length=20, verbose_name='Origem')),
                ('source_detail', models.CharField(blank=True, max_length=255, verbose_name='Detalhe da origem')),
                ('sync_hosp', models.BooleanField(default=False, verbose_name='Sincronizou internações?')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Linhas lidas')),
                ('beds_created', models.IntegerField(default=0, verbose_name='Leitos criados')),
                ('beds_updated', models.IntegerField(default=0, verbose_name='Leitos atualizados')),
                ('patients_created', models.IntegerField(default=0, verbose_name='Pacientes criados')),
                ('patients_updated', models.IntegerField(default=0, verbose_name='Pacientes atualizados')),
                ('hosp_created', models.IntegerField(default=0, verbose_name='Internações criadas')),
                ('hosp_closed', models.IntegerField(default=0, verbose_name='Internações encerradas')),
                ('vacant_beds', models.IntegerField(default=0, verbose_name='Leitos vagos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da importação')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Executado por')),
            ],
            options={
                'verbose_name': 'Log de Importação do Censo',
                'verbose_name_plural': 'Logs de Importação do Censo',
                'ordering': ['-created_at'],
            },
        ),
    ]
